# Generated by Django 5.0.2 on 2024-02-19 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0004_remove_user_role_user_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='roles.role'),
        ),
    ]
