# Generated by Django 5.0.2 on 2024-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_available_slots'),
        ('users', '0008_user_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(related_name='shifts', to='shifts.shift'),
        ),
    ]
