# Generated by Django 5.0.2 on 2024-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_accepted_users_shift_created_at_and_more'),
        ('users', '0011_remove_user_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='users', to='shifts.shift'),
        ),
    ]
