# Generated by Django 5.0.2 on 2024-02-20 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_accepted_users_shift_created_at_and_more'),
        ('users', '0012_user_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shifts',
        ),
        migrations.AddField(
            model_name='user',
            name='shifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shifts.shift'),
        ),
    ]
