# Generated by Django 5.0.2 on 2024-02-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securityPersonnel', '0003_remove_security_experience_security_phone_number_and_more'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_shifts', to='securityPersonnel.security')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_bids', to='shifts.shift')),
            ],
        ),
    ]
