# Generated by Django 5.0.2 on 2024-02-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
