# Generated by Django 5.0.2 on 2024-02-19 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
        ('securityPersonnel', '0002_security_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='experience',
        ),
        migrations.AddField(
            model_name='security',
            name='phone_number',
            field=models.CharField(default=4407544644733, max_length=30, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^(\\+\\d{1,3})?[\\s.-]?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='security',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='security',
            name='qualifications',
            field=models.ManyToManyField(related_name='owned_qualifications', to='qualifications.qualification'),
        ),
    ]
