# Generated by Django 5.0.2 on 2024-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityPersonnel', '0003_remove_security_experience_security_phone_number_and_more'),
        ('shifts', '0003_shift_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='shift',
            field=models.ManyToManyField(related_name='accepted_shifts', to='shifts.shift'),
        ),
    ]
